version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=data
    tty: true
    container_name: go_db
  redis:
    image: redis
    command: redis-server --requirepass AVITO_TEST
    ports:
      - 6379:6379
    tty: true
    container_name: go_redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    tty: true
    container_name: go_adminer
  app:
    build:
      context: ./cmd/auto
    volumes:
      - "./:/go/src/github.com/demsasha4yt/auto-backend-trainee-assignment"
    container_name: go_app
    ports:
      - "3000:3000"
    tty: true
    links:
      - db
      - redis
